/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_wangxi_ffmpegtest_VideoUtils */

#ifndef _Included_com_example_wangxi_ffmpegtest_VideoUtils
#define _Included_com_example_wangxi_ffmpegtest_VideoUtils

#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_wangxi_ffmpegtest_VideoUtils
 * Method:    decode
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_wangxi_ffmpegtest_VideoUtils_decode
  (JNIEnv *, jclass, jstring, jstring);

JNIEXPORT int JNICALL
Java_com_example_wangxi_ffmpegtest_VideoUtils_videoOut(JNIEnv *env, jclass type, jstring input_,jstring output_);

#ifdef __cplusplus
}
#endif
#endif
